baseURL = 'https://dev-loper99.github.io/'
languageCode = 'en-us'
title = 'Dev E. Loper #99'
theme = 'papermod'

copyright = '[© 2023 Dev E. Loper #99 & Assoc.](/copyright/)'

# custom menu entries menu
[[menu.main]]
identifier = 'fork'
name = 'Fork/PR'
url = 'https://github.com/dev-loper99/dev-loper99.github.io/fork'
weight = 100

[[menu.main]]
identifier = 'Issues'
name = 'issues'
url = 'https://github.com/dev-loper99/dev-loper99.github.io/issues'
weight = 101

# params
[params]
hideFooter = true

[params.profileMode]
enabled = true
title = "Dev E. Loper #99"

[[params.socialIcons]]
name = "github"
url = "https://github.com/dev-loper99"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/dev_loper99"
