# base
baseURL = 'https://dev-loper99.github.io/'
languageCode = 'en-us'
title = 'Dev E. Loper #99'
theme = 'papermod'

# menu
[[menu.main]]
identifier = 'about'
name = 'about'
url = '/about/'
weight = 10

# params
[params.profileMode]
enabled = true
title = "Dev E. Loper #99"
imageUrl = "https://pbs.twimg.com/profile_images/1729021170152779776/9PAaIT8w_400x400.jpg"
imageTitle = "Dev E. Loper #99"
imageWidth = 200
imageHeight = 200

[[params.profileMode.buttons]]
name = 'about'
url = '/about'

[[params.socialIcons]]
name = "github"
url = "https://github.com/dev-loper99"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/dev_loper99"
